name : Docker-CI
trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  ImageName: 'mfarhan1998/dotnet-test:$(Build.BuildId)'
 
stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
   
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub'
        repository: 'mfarhan1998/dotnet-test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'